Vagrant.configure(2) do |config|

  config.vm.define :vm do |v|
    v.vm.box = "samdoran/rhel7"

    v.vm.network "private_network", type: "dhcp"

    v.vm.hostname = "hostname.vagrant.com"

    v.vm.provider :virtualbox do |p|
      p.memory = 1024
      p.customize ["modifyvm", :id, "--paravirtprovider", "kvm"]
    end
  end

  config.vm.provision "ansible" do |a|
    a.playbook = "tests/vagrant.yml"
  end

end
